name: CI

on:
  # Trigger CI on push to any branch
  push:

  # Trigger CI every Monday at 12:21 p.m.
  schedule:
    - cron:  '21 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: [latest, minimal]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.tag }}
          file: Dockerfile
          tags: dhna/latex_slim:${{ matrix.tag }}
          push: true
